


### Security Requests



###
POST /api/v1/security/login
Host: localhost:9000
Authorization: Basic burgasvv@gmail.com burgasvv

###
POST /api/v1/security/logout
Host: localhost:9000



### Identity Requests



###
PUT /api/v1/identities/change-password
Host: localhost:9000
Content-Type: application/json

{
    "id": "6d8c7d99-0a45-454d-9bf2-cc0c8d2bd079",
    "password": "burgasvv"
}

###
PUT /api/v1/identities/change-status
Host: localhost:9000
Content-Type: application/json

{
    "id": "4fb21934-d4cb-42b2-803c-888d104ef46d",
    "status": true
}



### Admin Requests



###
GET /api/v1/admins
Host: localhost:9000

###
GET /api/v1/admins/by-id?adminId=a091ed91-7446-4009-a160-02b4a1d556b0
Host: localhost:9000

###
POST /api/v1/admins/create
Host: localhost:9000
Content-Type: application/json

{
    "identity": {
        "email": "zagor@gmail.com",
        "password": "zagor",
        "phone": "+79563214589",
        "firstname": "Загорулько",
        "lastname": "Борис",
        "patronymic": "Юрьевич"
    }
}

###
PUT /api/v1/admins/update
Host: localhost:9000
Content-Type: application/json

{
    "id": "ce3fc235-91a9-45a2-9cfb-9d35c9ed0ff8",
    "identity": {
        "phone": "+75461239674"
    }
}

###
DELETE /api/v1/admins/delete?adminId=ce3fc235-91a9-45a2-9cfb-9d35c9ed0ff8
Host: localhost:9000



### Patient Requests



###
GET /api/v1/patients
Host: localhost:9000

###
GET /api/v1/patients/by-id?patientId=23e26053-084c-4d1b-b08b-c03219d15817
Host: localhost:9000

###
POST /api/v1/patients/create
Host: localhost:9000
Content-Type: application/json

{
    "identity": {
        "email": "osipkin@gmail.com",
        "password": "osipkin",
        "phone": "+79563214578",
        "firstname": "Осипкин",
        "lastname": "Алексей",
        "patronymic": "Олегович"
    },
    "passport": "4567 908754"
}

###
PUT /api/v1/patients/update
Host: localhost:9000
Content-Type: application/json

{
    "id": "23e26053-084c-4d1b-b08b-c03219d15817",
    "passport": "1985 982475"
}

###
DELETE /api/v1/patients/delete?patientId=afa5e35e-bbe3-4d9d-8256-f305148d1eba
Host: localhost:9000



### Department Requests



###
GET /api/v1/departments
Host: localhost:9000

###
GET /api/v1/departments/by-id?departmentId=cce124e9-84e9-4d87-a2bf-6d0ad40e5561
Host: localhost:9000

###
POST /api/v1/departments/create
Host: localhost:9000
Content-Type: application/json

{
    "name": "Отделение Кардиологии",
    "description": "Специальное кардиологическое медицинское подразделение"
}

###
PUT /api/v1/departments/update
Host: localhost:9000
Content-Type: application/json

{
    "id": "108cd37f-3527-46cb-8d04-c501e2543304",
    "description": "Специальное кардиологическое медицинское подразделение"
}

###
DELETE /api/v1/departments/delete?departmentId=108cd37f-3527-46cb-8d04-c501e2543304
Host: localhost:9000



### Category Requests



###
GET /api/v1/categories/by-id?categoryId=4e81afff-5be6-45b1-9214-15cab6d6c16c
Host: localhost:9000

###
POST /api/v1/categories/create
Host: localhost:9000
Content-Type: application/json

{
    "name": "Кардиолог",
    "description": "Специалист, который занимается диагностикой, лечением и профилактикой заболеваний сердца и кровеносных сосудов.",
    "departmentId": "cce124e9-84e9-4d87-a2bf-6d0ad40e5561"
}

###
PUT /api/v1/categories/update
Host: localhost:9000
Content-Type: application/json

{
    "id": "3ccaad00-aa6d-4215-92eb-98cb283b4da1",
    "description": "Специалист, который занимается диагностикой, лечением и профилактикой заболеваний сердца и кровеносных сосудов."
}

###
DELETE /api/v1/categories/delete?categoryId=3ccaad00-aa6d-4215-92eb-98cb283b4da1
Host: localhost:9000